"""
Feature importance + SHAP + Optuna selection 통합 시각화.
==========================================================

Optuna feature selection 의 binary mask 결과 (true/false 빈도) +
R11(shap) SHAP 값 + 모델별 feature_importances_ 를 한 화면에서 비교.

질문: "어느 feature 가 어느 모델에 얼마나 중요한가?"

생성되는 figures (매 모델별):
  1. **bar plot** — Optuna selection frequency (across N trials)
  2. **bar plot** — SHAP |value| top-30
  3. **scatter overlay** — Optuna freq vs SHAP importance
  4. **heatmap** — feature × model importance (전체 모델 비교)
  5. **Sankey-ish flow** — mandatory → binary mask → composite → final selected
  6. **mandatory vs optional split** — 38 mandatory 의 SHAP vs binary candidate

CLI:
    python -m simulation feature-importance                  # 모든 챔피언
    python -m simulation feature-importance --models XGBoost,LightGBM
    python -m simulation feature-importance --top-k 30
    python -m simulation feature-importance --no-shap        # SHAP skip (faster)
"""
from __future__ import annotations

import json
import logging
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import numpy as np

log = logging.getLogger(__name__)


def _setup_mpl():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({
        "figure.dpi": 110,
        "savefig.dpi": 140,
        "font.size": 9.5,
        "axes.titlesize": 11,
        "axes.labelsize": 9.5,
        "axes.grid": True,
        "grid.alpha": 0.25,
    })
    return plt


# ─────────────────────────────────────────────────────────────────
# 1. Optuna binary-mask frequency from study DB
# ─────────────────────────────────────────────────────────────────
def _read_optuna_feature_freq(model_name: str,
                                 db_path: Path) -> dict[str, float]:
    """Read optuna_feat_freq_<model>.json if it exists.

    Format: {feature_name: frequency_in_top_trials} where freq ∈ [0, 1].
    Generated by R9 per_model_optimize (tools/run_optuna_feature_selection.py).
    """
    candidates = [
        db_path.parent / f"optuna_feat_freq_{model_name.lower()}.json",
        db_path.parent / f"optuna_feat_freq_{model_name}.json",
        db_path.parent / f"optuna_feat_freq_{model_name.replace('-','_').lower()}.json",
    ]
    for p in candidates:
        if p.exists():
            try:
                return json.loads(p.read_text())
            except Exception as e:
                log.warning(f"  [feat-imp] {p} read fail: {e}")
    return {}


def _compute_optuna_freq_from_db(study_name: str,
                                     db_path: Path,
                                     top_k_trials: int = 25) -> dict[str, float]:
    """Compute feature selection frequency from the top-k trials in a study.

    Each trial's params has `use_<feat> = True/False` keys. We count the
    fraction of top trials (by objective) where each feature was selected.
    """
    try:
        import optuna
        storage = f"sqlite:///{db_path}"
        study = optuna.load_study(study_name=study_name, storage=storage)
    except Exception as e:
        log.warning(f"  [feat-imp] could not load study '{study_name}': {e}")
        return {}

    completed = [t for t in study.trials if t.value is not None]
    if not completed:
        return {}
    completed.sort(key=lambda t: t.value)
    top_k = completed[:min(top_k_trials, len(completed))]

    feat_count: dict[str, int] = {}
    for t in top_k:
        for k, v in (t.params or {}).items():
            if not k.startswith("use_"):
                continue
            feat = k[4:]
            feat_count[feat] = feat_count.get(feat, 0) + (1 if v else 0)
    n = len(top_k)
    return {f: c / n for f, c in feat_count.items()}


# ─────────────────────────────────────────────────────────────────
# 2. SHAP from R11(shap) output (feature_importance.json)
# ─────────────────────────────────────────────────────────────────
def _read_shap_importance(model_name: str,
                              shap_dir: Path) -> dict[str, float]:
    """Read SHAP-based importance for a model from R11(shap) output."""
    from simulation.utils.paths import get_results_dir  # SSOT MPH_OUTPUT_ROOT (2026-05-29)
    candidates = [
        shap_dir / "feature_importance.json",
        shap_dir / f"shap_{model_name}.json",
        get_results_dir() / "checkpoints" / "checkpoint_phase8.json",
    ]
    for p in candidates:
        if not p.exists():
            continue
        try:
            j = json.loads(p.read_text())
            # R11(shap) 의 일반적 형식: {model: [{feature, score}, ...]}
            if "data" in j and "feature_importance" in j["data"]:
                fi = j["data"]["feature_importance"]
                mi = fi.get("model_importance", {})
                if model_name in mi:
                    return {item["feature"]: float(item["score"])
                            for item in mi[model_name]}
            elif isinstance(j, dict) and "model_importance" in j:
                mi = j["model_importance"]
                if model_name in mi:
                    return {item["feature"]: float(item["score"])
                            for item in mi[model_name]}
            elif "shap_values" in j or "importance" in j:
                if "importance" in j:
                    return {item["feature"]: float(item["score"])
                            for item in j["importance"]}
        except Exception as e:
            log.debug(f"  [feat-imp] SHAP read {p}: {e}")
    return {}


# ─────────────────────────────────────────────────────────────────
# 3. Plotting
# ─────────────────────────────────────────────────────────────────
def _plot_feat_overlap(model_name: str,
                          optuna_freq: dict, shap_imp: dict,
                          mandatory: set, top_k: int,
                          out_path: Path) -> None:
    """3-panel: Optuna freq bar, SHAP bar, scatter overlap."""
    plt = _setup_mpl()
    fig, axes = plt.subplots(1, 3, figsize=(18, 5.5))

    # 1. Optuna selection frequency (top-k by freq)
    if optuna_freq:
        top = sorted(optuna_freq.items(), key=lambda x: -x[1])[:top_k]
        feats, freqs = zip(*top)
        colors = ["#1976d2" if f in mandatory else "#ff9800" for f in feats]
        ax = axes[0]
        ax.barh(range(len(feats))[::-1], freqs, color=colors, edgecolor="k", lw=0.4)
        ax.set_yticks(range(len(feats))[::-1])
        ax.set_yticklabels(feats, fontsize=8)
        ax.set_xlabel("Optuna selection frequency (top-25 trials)")
        ax.set_title(f"{model_name} — Optuna feature mask freq")
        ax.set_xlim(0, 1.05)
        # Legend
        from matplotlib.patches import Patch
        ax.legend(handles=[Patch(color="#1976d2", label="mandatory"),
                            Patch(color="#ff9800", label="optional (binary)")],
                  fontsize=8, loc="lower right")
    else:
        axes[0].text(0.5, 0.5, "No Optuna freq data\n(study DB 미발견)",
                     ha="center", va="center", transform=axes[0].transAxes)
        axes[0].set_title(f"{model_name} — Optuna freq (n/a)")

    # 2. SHAP top-k
    if shap_imp:
        top = sorted(shap_imp.items(), key=lambda x: -abs(x[1]))[:top_k]
        feats, vals = zip(*top)
        colors = ["#1976d2" if f in mandatory else "#4caf50" for f in feats]
        ax = axes[1]
        ax.barh(range(len(feats))[::-1], vals, color=colors, edgecolor="k", lw=0.4)
        ax.set_yticks(range(len(feats))[::-1])
        ax.set_yticklabels(feats, fontsize=8)
        ax.set_xlabel("|SHAP value| (or feature_importances_)")
        ax.set_title(f"{model_name} — SHAP / feature importance")
    else:
        axes[1].text(0.5, 0.5, "No SHAP data\n(R11 shap 미수행)",
                     ha="center", va="center", transform=axes[1].transAxes)
        axes[1].set_title(f"{model_name} — SHAP (n/a)")

    # 3. Scatter overlap (Optuna freq vs SHAP)
    if optuna_freq and shap_imp:
        common = set(optuna_freq.keys()) & set(shap_imp.keys())
        if common:
            xs = [optuna_freq[f] for f in common]
            ys = [abs(shap_imp[f]) for f in common]
            colors = ["#1976d2" if f in mandatory else "#9c27b0" for f in common]
            ax = axes[2]
            ax.scatter(xs, ys, s=22, c=colors, edgecolor="k", lw=0.4, alpha=0.8)
            # Top-N annotate
            top_combined = sorted(common,
                                    key=lambda f: -(optuna_freq[f] * abs(shap_imp[f])))[:8]
            for f in top_combined:
                ax.annotate(f, xy=(optuna_freq[f], abs(shap_imp[f])),
                              xytext=(3, 3), textcoords="offset points",
                              fontsize=7, alpha=0.85)
            ax.set_xlabel("Optuna selection freq")
            ax.set_ylabel("|SHAP value|")
            ax.set_title(f"{model_name} — Optuna ⊗ SHAP")
            ax.set_xlim(-0.05, 1.05)
        else:
            axes[2].text(0.5, 0.5, "No overlap (Optuna ∩ SHAP)",
                         ha="center", va="center", transform=axes[2].transAxes)
    else:
        axes[2].text(0.5, 0.5, "Need both Optuna + SHAP",
                     ha="center", va="center", transform=axes[2].transAxes)
        axes[2].set_title(f"{model_name} — overlap (n/a)")

    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def _plot_heatmap_model_x_feature(per_model_imp: dict[str, dict],
                                       top_k: int,
                                       mandatory: set,
                                       out_path: Path) -> None:
    """Heatmap: rows = top features (union), cols = models, values = importance."""
    if not per_model_imp:
        return
    plt = _setup_mpl()
    # Union top-k from each model
    union_features = set()
    for m, imp in per_model_imp.items():
        top_feats = sorted(imp.items(), key=lambda x: -abs(x[1]))[:top_k]
        union_features.update(f for f, _ in top_feats)
    union_features = sorted(union_features)
    if not union_features:
        return

    models = sorted(per_model_imp.keys())
    M = np.zeros((len(union_features), len(models)))
    for j, m in enumerate(models):
        imp = per_model_imp[m]
        # Normalize within model
        max_v = max(abs(v) for v in imp.values()) if imp else 1.0
        if max_v == 0:
            max_v = 1.0
        for i, f in enumerate(union_features):
            M[i, j] = abs(imp.get(f, 0)) / max_v

    fig, ax = plt.subplots(figsize=(max(8, len(models) * 0.6),
                                     max(6, len(union_features) * 0.22)))
    im = ax.imshow(M, aspect="auto", cmap="viridis", vmin=0, vmax=1)
    ax.set_xticks(range(len(models)))
    ax.set_xticklabels(models, rotation=45, ha="right", fontsize=8)
    ax.set_yticks(range(len(union_features)))
    ax.set_yticklabels(
        [f"⭐ {f}" if f in mandatory else f for f in union_features],
        fontsize=7.5,
    )
    ax.set_xlabel("model")
    ax.set_ylabel("feature (⭐ = mandatory)")
    ax.set_title(f"Feature importance heatmap (normalized within model, "
                  f"union of top-{top_k} per model)")
    plt.colorbar(im, ax=ax, label="normalized |importance|")
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


def _plot_mandatory_vs_optional(per_model_imp: dict, mandatory: set,
                                    out_path: Path) -> None:
    """Box plot: importance distribution, mandatory vs optional, per model."""
    if not per_model_imp:
        return
    plt = _setup_mpl()
    fig, ax = plt.subplots(figsize=(12, 6))
    pos = 1
    labels: list[str] = []
    for m in sorted(per_model_imp.keys()):
        imp = per_model_imp[m]
        if not imp:
            continue
        mand_vals = [abs(v) for f, v in imp.items() if f in mandatory]
        opt_vals = [abs(v) for f, v in imp.items() if f not in mandatory]
        if not (mand_vals and opt_vals):
            continue
        # Normalize
        max_v = max(max(mand_vals), max(opt_vals))
        if max_v > 0:
            mand_vals = [v / max_v for v in mand_vals]
            opt_vals = [v / max_v for v in opt_vals]
        ax.boxplot([mand_vals, opt_vals],
                    positions=[pos, pos + 0.4], widths=0.35,
                    patch_artist=True,
                    boxprops=dict(facecolor="#1976d2", alpha=0.6),
                    medianprops=dict(color="black"),
                    flierprops=dict(marker="o", markersize=2))
        # Different color for second box
        ax.boxplot([opt_vals], positions=[pos + 0.4], widths=0.35,
                   patch_artist=True,
                   boxprops=dict(facecolor="#ff9800", alpha=0.6),
                   medianprops=dict(color="black"),
                   flierprops=dict(marker="o", markersize=2))
        labels.append(m)
        pos += 1.2
    if labels:
        ax.set_xticks([1.2 * i + 1.2 for i in range(len(labels))])
        ax.set_xticklabels(labels, rotation=45, ha="right", fontsize=8)
        from matplotlib.patches import Patch
        ax.legend(handles=[
            Patch(color="#1976d2", alpha=0.6, label="mandatory (38)"),
            Patch(color="#ff9800", alpha=0.6, label="optional binary"),
        ], fontsize=9, loc="upper right")
    ax.set_ylabel("normalized |importance|")
    ax.set_title("Mandatory vs Optional feature importance distribution per model")
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────
# 4. Public entry
# ─────────────────────────────────────────────────────────────────
def run_feature_importance(*, models_filter: Optional[list[str]] = None,
                              top_k: int = 30,
                              include_shap: bool = True,
                              out_dir: Optional[Path] = None,
                              repo_root: Optional[Path] = None) -> dict:
    """Generate Optuna freq + SHAP integrated visualizations."""
    if repo_root is None:
        repo_root = Path.cwd()
    repo_root = Path(repo_root)
    if out_dir is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_dir = repo_root / "simulation" / "results" / "feature_importance" / ts
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    t0 = time.time()
    log.info(f"[feat-imp] output → {out_dir}")

    # Mandatory features set
    try:
        from simulation.tools.run_optuna_feature_selection import (
            MANDATORY_FEATURES_EXACT,
        )
        mandatory = set(MANDATORY_FEATURES_EXACT)
    except Exception:
        mandatory = set()

    # Champion list
    from simulation.utils.champion_log import ChampionLog
    cl = ChampionLog(models_dir=repo_root / "models",
                       log_path=repo_root / "models" / "champion_log.json")
    sm = cl.summary()
    if not sm:
        log.warning("[feat-imp] no champions in log")
        return {"skipped": True, "reason": "no champions"}
    if models_filter:
        sm = {k: v for k, v in sm.items() if k in models_filter}

    # Optuna study DB path
    db_path = repo_root / "simulation" / "results" / "optuna_feature_selection.db"
    shap_dir = repo_root / "simulation" / "results"

    per_model_optuna: dict[str, dict] = {}
    per_model_shap: dict[str, dict] = {}
    figures: list[dict] = []

    for nm in sorted(sm.keys()):
        # 1. Optuna freq — JSON 우선, 없으면 DB 에서 직접 계산
        of = _read_optuna_feature_freq(nm, db_path)
        if not of and db_path.exists():
            for sn in (f"feat_only_{nm.lower()}_v15",
                         f"joint_{nm.lower()}_v15",
                         f"feat_only_{nm.lower().replace('-','_')}_v15"):
                of = _compute_optuna_freq_from_db(sn, db_path, top_k_trials=25)
                if of:
                    break
        per_model_optuna[nm] = of

        # 2. SHAP / feature importance
        si = {}
        if include_shap:
            si = _read_shap_importance(nm, shap_dir)
        per_model_shap[nm] = si

        # 3. Per-model 3-panel
        out_p = out_dir / f"{nm}_feat_importance.png"
        try:
            _plot_feat_overlap(nm, of, si, mandatory, top_k, out_p)
            figures.append({"model": nm, "kind": "per_model_3panel",
                              "path": str(out_p)})
        except Exception as e:
            log.warning(f"[feat-imp] {nm} per-model plot failed: {e}")

    # 4. Heatmap (model × feature) — SHAP 우선, 없으면 Optuna freq
    main_imp = {m: per_model_shap.get(m) or per_model_optuna.get(m)
                for m in sm.keys()}
    main_imp = {m: v for m, v in main_imp.items() if v}
    if main_imp:
        try:
            _plot_heatmap_model_x_feature(main_imp, top_k, mandatory,
                                                out_dir / "heatmap_model_x_feature.png")
            figures.append({"kind": "heatmap_model_x_feature",
                              "path": str(out_dir / "heatmap_model_x_feature.png")})
        except Exception as e:
            log.warning(f"[feat-imp] heatmap failed: {e}")

        try:
            _plot_mandatory_vs_optional(main_imp, mandatory,
                                             out_dir / "mandatory_vs_optional.png")
            figures.append({"kind": "mandatory_vs_optional",
                              "path": str(out_dir / "mandatory_vs_optional.png")})
        except Exception as e:
            log.warning(f"[feat-imp] mandatory_vs_optional failed: {e}")

    # 5. Manifest + INDEX.md
    manifest = {
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "n_models":  len(per_model_optuna),
        "top_k":     top_k,
        "n_mandatory": len(mandatory),
        "include_shap": include_shap,
        "figures":   figures,
        "data_summary": {
            m: {
                "optuna_freq_n":  len(per_model_optuna.get(m, {})),
                "shap_n":         len(per_model_shap.get(m, {})),
            } for m in sorted(sm.keys())
        },
    }
    (out_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, default=str))

    md = ["# Feature Importance — Optuna selection ⊗ SHAP", "",
          f"- Generated: {manifest['generated']}",
          f"- Champions: {manifest['n_models']}",
          f"- Top-K: {top_k}",
          f"- Mandatory features: {manifest['n_mandatory']}",
          ""]
    md.append("## Heatmap (model × feature)")
    if (out_dir / "heatmap_model_x_feature.png").exists():
        md.append("![heatmap](heatmap_model_x_feature.png)")
    md.append("")
    md.append("## Mandatory vs Optional distribution")
    if (out_dir / "mandatory_vs_optional.png").exists():
        md.append("![mvso](mandatory_vs_optional.png)")
    md.append("")
    md.append("## Per-model 3-panel (Optuna freq | SHAP | overlap)")
    for nm in sorted(per_model_optuna.keys()):
        s = manifest["data_summary"].get(nm, {})
        md.append(f"### {nm}")
        md.append(f"- Optuna freq features: {s.get('optuna_freq_n', 0)}, "
                  f"SHAP: {s.get('shap_n', 0)}")
        md.append(f"![{nm}_fi]({nm}_feat_importance.png)")
        md.append("")
    (out_dir / "INDEX.md").write_text("\n".join(md))

    elapsed = time.time() - t0
    log.info(f"[feat-imp] {len(figures)} figures in {elapsed:.1f}s")
    return {
        "out_dir":  str(out_dir),
        "n_figures": len(figures),
        "n_models":  len(per_model_optuna),
        "elapsed":   elapsed,
        "index_md":  str(out_dir / "INDEX.md"),
    }


__all__ = ["run_feature_importance"]
