/**
 * Hermes — the cross-provider orchestrator. Four modes:
 *
 * - **solo**       — single provider, streams directly.
 * - **parallel**   — fan out to N providers, interleave their events
 *                    with a ``providerId`` tag so the UI can render
 *                    columns side by side.
 * - **synthesis**  — fan out in parallel, then once every provider
 *                    reaches ``done`` ask a ``synthesiser`` provider to
 *                    reconcile the answers into one.
 * - **relay**      — sequentially chain providers, feeding each reply
 *                    as a ``[Previous from X]`` prefixed user turn into
 *                    the next provider (so they can critique / extend).
 *
 * All four share a single upstream ``ReadableStream`` of ``StreamEvent``
 * objects tagged with ``providerId``. The route handler re-serialises
 * them to SSE for the browser.
 */

import { listTools } from "./mcp-client";
import { getProvider, getProviders } from "./providers/registry";
import ariaWiki from "./aria-wiki.json";
import type {
  ChatMessage,
  CompletionRequest,
  ProviderId,
  ResponseMode,
  StreamEvent,
  ToolSpec,
} from "./providers/types";

export type TaggedEvent = StreamEvent & { providerId: ProviderId };

export interface HermesRequest {
  mode: ResponseMode;
  messages: ChatMessage[];
  providers: Array<{ id: ProviderId; model: string; temperature?: number }>;
  /**
   * For ``synthesis`` mode only — which provider writes the final
   * reconciliation. Must be present in ``providers``.
   */
  synthesiser?: ProviderId;
  /** Abort from the route handler — propagated to every provider. */
  signal?: AbortSignal;
}

// Layered citation policy (2026-05-07): Vercel deploy default has NO MCP
// (Python-based stdio bridge can't run on Edge). Without a fallback path,
// ARIA refuses every numeric question with "tools unavailable" — useless
// for the 30 user × 12h prototype day. So we instruct the LLM to fall
// through tiers: MCP → baked data digest → sim context → training KB.
// [법령·KDCA wiki] — generated by build_aria_wiki.py (감염병예방법 framework +
// 질병관리청 surveillance facts). Appended to every provider/mode's system
// prompt so each LLM grounds Korean-law / 법정감염병 / 신고 / 방역 / 예방접종
// claims in real statute + KDCA data instead of hallucinating.
const W = ariaWiki as {
  law: {
    name: string;
    authority: string;
    classification: string;
    provisions: string[];
    sources: string[];
    caveat: string;
  };
  kdca_data: {
    influenza?: { legal_grade: string; transmission: string; vaccine_available: boolean };
    sentinel_ili_latest?: {
      season: number;
      week: string;
      age_group: string;
      ili_rate: number;
      unit: string;
    };
  };
};
const KDCA_WIKI =
  "\n\n[법령·KDCA wiki] — 한국 감염병 법령 + 질병관리청 사실 (이 블록을 1차 근거로; 조문·등급 환각 금지):\n" +
  `· 법: ${W.law.name}, 소관 ${W.law.authority}.\n` +
  `· 분류: ${W.law.classification}\n` +
  W.law.provisions.map((p) => `· ${p}`).join("\n") +
  (W.kdca_data.influenza
    ? `\n· KDCA disease_master: 인플루엔자=${W.kdca_data.influenza.legal_grade}, ${W.kdca_data.influenza.transmission}, 백신 ${W.kdca_data.influenza.vaccine_available ? "있음" : "없음"}.`
    : "") +
  (W.kdca_data.sentinel_ili_latest
    ? `\n· 최근 표본감시 ILI: ${W.kdca_data.sentinel_ili_latest.season}절기 ${W.kdca_data.sentinel_ili_latest.week} ${W.kdca_data.sentinel_ili_latest.age_group} ${W.kdca_data.sentinel_ili_latest.ili_rate} (${W.kdca_data.sentinel_ili_latest.unit}).`
    : "") +
  `\n· 출처: ${W.law.sources.join("; ")}. ${W.law.caveat}`;

const SYSTEM_GROUNDING =
  "You are the ARIA consultant for the Seoul flu forecasting project. " +
  "Citation policy for numeric / district / disease / date claims — try " +
  "tiers in order, never refuse just because the top tier is missing:\n" +
  "  1. MCP tools when available (epi.query_db, epi.forecast, " +
  "epi.rt_estimate, epi.scenario_run, epi.validity_check, " +
  "epi.literature_rag) — cite [tool:<name>].\n" +
  "  1b. [법령·KDCA wiki] block (아래 첨부) — 한국 감염병예방법 + 질병관리청 " +
  "사실(법정등급·표본감시·신고·방역조치·예방접종). 한국 법령 / 법정감염병 / 신고 / " +
  "방역 / 예방접종 관련 주장은 이 블록을 우선 인용 — [law:감염병예방법] 또는 " +
  "[data:KDCA]. 조문 번호나 감염병 등급을 임의로 지어내지 말 것.\n" +
  "  2. The [실데이터 digest] block in the user-supplied system prompt " +
  "(real numbers baked from epi_real_seoul.db at deploy time) — " +
  "cite [tool:data_digest].\n" +
  "  3. The [현재 컨텍스트] block (sim day / selected gu / scenario) — " +
  "cite [tool:sim_context].\n" +
  "  4. Established epi knowledge (KDCA / WHO / peer-reviewed " +
  "meta-analyses, Claude training cutoff) with explicit caveat — " +
  "cite [기존 문헌].\n" +
  "Always state which tier the evidence came from. For simulation / " +
  "prediction asks where MCP is unavailable, do hand-calculation from " +
  "digest + SEIR knowledge and prepend '(추정 — 실 모델 미연동)'.\n" +
  "  [운영 모드 라우팅] If the system prompt's [운영 모드] block reports " +
  "WATCH or PANDEMIC, the mechanistic SEIR/ABM (seir-forecast-360) is the " +
  "authoritative forecast. Under PANDEMIC the ML nowcast (ili-forecast) is " +
  "out-of-range extrapolation — cite it only as reference, never present its " +
  "peak/attack-rate as the authoritative forecast; answer forecasts from the " +
  "mechanistic SEIR/ABM. Under WATCH, present ML nowcast plus the parallel " +
  "mechanistic scenario and caveat possible escalation.\n" +
  "  [연령별 위험] Age-specific risk (어느 연령대가 위험한가) comes ONLY from the " +
  "validated WAIFW age-structured SEIR (age-seir-forecast / [연령별 위험] block in the " +
  "system prompt) — school-age (10-19) highest, elderly (60+) lowest, validated against " +
  "real sentinel age-ILI at Spearman ρ≈0.68. Cite those model numbers; do not invent age " +
  "attack rates. State it is a seasonal-calibrated baseline (the relative age gradient is " +
  "what is validated, not the absolute %)." +
  KDCA_WIKI;

/**
 * Stream orchestrator output as a single ReadableStream of tagged
 * events. Consumers (the SSE route) can call ``reader.read()`` until
 * EOF; each chunk is a single JSON object line.
 */
export function runHermes(req: HermesRequest): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();

  return new ReadableStream({
    async start(controller) {
      const write = (evt: TaggedEvent) => {
        controller.enqueue(encoder.encode(JSON.stringify(evt) + "\n"));
      };

      let tools: ToolSpec[] = [];
      try {
        tools = await listTools({ signal: req.signal });
      } catch (e) {
        // Tools are optional — providers can still answer without MCP
        // if the bridge is down.
        write({
          providerId: "anthropic",
          type: "status",
          level: "warn",
          message: `mcp bridge unavailable: ${errMsg(e)}`,
        });
      }

      const systemPrefix: ChatMessage = {
        role: "system",
        content: SYSTEM_GROUNDING,
      };
      const baseMessages = [systemPrefix, ...req.messages];

      try {
        switch (req.mode) {
          case "solo":
            await runSolo(req, baseMessages, tools, write);
            break;
          case "parallel":
            await runParallel(req, baseMessages, tools, write);
            break;
          case "synthesis":
            await runSynthesis(req, baseMessages, tools, write);
            break;
          case "relay":
            await runRelay(req, baseMessages, tools, write);
            break;
          default:
            write({
              providerId: req.providers[0]?.id ?? "anthropic",
              type: "error",
              message: `unknown mode: ${req.mode}`,
            });
        }
      } catch (e) {
        write({
          providerId: req.providers[0]?.id ?? "anthropic",
          type: "error",
          message: errMsg(e),
        });
      } finally {
        controller.close();
      }
    },
  });
}

// ── Mode implementations ─────────────────────────────────────────────
async function runSolo(
  req: HermesRequest,
  messages: ChatMessage[],
  tools: ToolSpec[],
  write: (e: TaggedEvent) => void,
): Promise<void> {
  const target = req.providers[0];
  if (!target) throw new Error("solo mode requires exactly one provider");
  const p = getProvider(target.id);
  const complete: CompletionRequest = {
    model: target.model,
    messages,
    temperature: target.temperature,
    tools,
    signal: req.signal,
  };
  for await (const evt of p.stream(complete)) {
    write({ ...evt, providerId: p.id });
  }
}

async function runParallel(
  req: HermesRequest,
  messages: ChatMessage[],
  tools: ToolSpec[],
  write: (e: TaggedEvent) => void,
): Promise<void> {
  const tasks = req.providers.map(async (t) => {
    const p = getProvider(t.id);
    const complete: CompletionRequest = {
      model: t.model,
      messages,
      temperature: t.temperature,
      tools,
      signal: req.signal,
    };
    for await (const evt of p.stream(complete)) {
      write({ ...evt, providerId: p.id });
    }
  });
  await Promise.allSettled(tasks);
}

async function runSynthesis(
  req: HermesRequest,
  messages: ChatMessage[],
  tools: ToolSpec[],
  write: (e: TaggedEvent) => void,
): Promise<void> {
  // 1. Fan-out in parallel, also buffering each provider's full text
  //    reply so we can feed it into the synthesiser.
  const texts = new Map<ProviderId, string>();
  const tasks = req.providers.map(async (t) => {
    const p = getProvider(t.id);
    const complete: CompletionRequest = {
      model: t.model,
      messages,
      temperature: t.temperature,
      tools,
      signal: req.signal,
    };
    let buf = "";
    for await (const evt of p.stream(complete)) {
      if (evt.type === "text") buf += evt.delta;
      write({ ...evt, providerId: p.id });
    }
    texts.set(p.id, buf);
  });
  await Promise.allSettled(tasks);

  // 2. Let the synthesiser reconcile. Default to the first available
  //    provider if ``synthesiser`` is unset.
  const synId = req.synthesiser ?? req.providers[0]?.id;
  if (!synId) return;
  const synTarget = req.providers.find((t) => t.id === synId);
  if (!synTarget) return;
  const p = getProvider(synTarget.id);
  const synPrompt: ChatMessage[] = [
    ...messages,
    ...[...texts.entries()].map(([pid, t]) => ({
      role: "user" as const,
      content: `[Previous from ${pid}]\n${t}`,
    })),
    {
      role: "user" as const,
      content:
        "Synthesise the above answers into one reconciled reply. " +
        "If any claim is contradicted across providers, surface the " +
        "contradiction rather than hide it. Cite MCP tools as [tool:<name>].",
    },
  ];
  for await (const evt of p.stream({
    model: synTarget.model,
    messages: synPrompt,
    temperature: 0.0,
    tools,
    signal: req.signal,
  })) {
    write({ ...evt, providerId: p.id });
  }
}

async function runRelay(
  req: HermesRequest,
  messages: ChatMessage[],
  tools: ToolSpec[],
  write: (e: TaggedEvent) => void,
): Promise<void> {
  let running: ChatMessage[] = [...messages];
  for (const target of req.providers) {
    const p = getProvider(target.id);
    let buf = "";
    for await (const evt of p.stream({
      model: target.model,
      messages: running,
      temperature: target.temperature,
      tools,
      signal: req.signal,
    })) {
      if (evt.type === "text") buf += evt.delta;
      write({ ...evt, providerId: p.id });
    }
    // Feed the reply to the next hop — prefix so downstream models
    // don't mistake the previous provider's text for their own prior
    // output (which confuses role tracking).
    running = [
      ...running,
      {
        role: "user",
        content: `[Previous from ${p.id}] ${buf}`,
        origin: p.id,
      },
    ];
  }
}

function errMsg(e: unknown): string {
  if (e instanceof Error) return `${e.name}: ${e.message}`;
  return String(e);
}

/**
 * Convenience used by ``ProviderPicker.tsx`` to know which providers
 * to show. Kept here so the UI doesn't need to import all adapter
 * modules (which pull in heavy SDKs).
 */
export function availableProviderIds(): ProviderId[] {
  return [...getProviders().values()]
    .filter((p) => p.available())
    .map((p) => p.id);
}
