/**
 * ``/api/overlays/live`` orchestrator.
 *
 * Fan-out to every provider via ``Promise.allSettled`` so one dead
 * upstream can't brick the map. Each provider returns either a
 * ``MetricPayload`` (live data), ``null`` (no API key → skip), or an
 * "offline"-flagged ``MetricPayload`` (tried but failed). For null
 * slots we synthesise a fallback — first from the bundled static
 * aggregate, then from a deterministic pseudo-generator so the
 * choropleth is *never* blank.
 *
 * Budget: each provider has a 3-4 s internal timeout; the orchestrator
 * itself waits on all of them in parallel, capped by the Edge route's
 * 30 s wall. Typical warm response when all keys are set: 300-600 ms.
 */

import type {
  LiveMetricId,
  LiveOverlaysResponse,
  MetricPayload,
} from "./types";
import { SEOUL_GU, classifyFreshness, tfetch } from "./types";

import { buildIliLiveAndAlert } from "./turso-ili";
import { buildTempAndHumidity } from "./kma-weather";
import { buildAir } from "./seoul-air";
import { buildEr } from "./nedis-er";
import { buildMetro } from "./metro-congestion";

/** How long the client should treat this response as "fresh enough". */
const TTL_SECONDS = 300;

/** Static aggregate from public/aggregates/live-overlays.json. We refer
 *  to it via a relative URL because Edge can't read the filesystem. */
const STATIC_FALLBACK_URL = "/aggregates/live-overlays.json";

interface StaticFallbackShape {
  generated_at?: string;
  metrics?: Partial<
    Record<
      "ili" | "air" | "temp",
      {
        label_ko: string;
        label_en: string;
        unit: string;
        source?: string;
        rows: Array<{ gu_nm: string; value: number }>;
      }
    >
  >;
}

/** Entry point. Uses the request's origin so the fetch for the static
 *  JSON doesn't hard-code a hostname — works in both dev and Vercel. */
export async function buildLiveOverlays(
  origin: string,
  signal: AbortSignal,
): Promise<LiveOverlaysResponse> {
  const [iliPair, tempHumPair, air, er, metro, staticFb] = await Promise.all([
    safe(() => buildIliLiveAndAlert(origin, signal), { live: null, alert: null }),
    safe(() => buildTempAndHumidity(signal), { temp: null, humidity: null }),
    safe(() => buildAir(signal), null),
    safe(() => buildEr(signal), null),
    safe(() => buildMetro(signal), null),
    fetchFallback(origin, signal),
  ]);

  const metrics: Partial<Record<LiveMetricId, MetricPayload>> = {};

  // ILI forecast — primary source is the model-forecast JSON generated by
  // build-static-aggregates.py (champion trained model → per-gu via ABM).
  // Falls back to the legacy static aggregate, then to the synthetic demo.
  const iliForecast = await safe(() => buildIliForecast(origin, signal), null);
  metrics.ili_forecast =
    iliForecast ??
    remapStatic(staticFb, "ili", {
      id: "ili_forecast",
      label_ko: "ILI 예측 (post_E v22.6)",
      label_en: "ILI forecast (post_E v22.6)",
      unit: "per 1k",
    }) ??
    synthesise("ili_forecast");

  metrics.ili_live =
    iliPair.live ??
    remapStatic(staticFb, "ili", {
      id: "ili_live",
      label_ko: "ILI 실측 (KDCA, fallback)",
      label_en: "ILI observed (KDCA, fallback)",
      unit: "/1k",
    }) ??
    synthesise("ili_live");

  metrics.ili_alert = iliPair.alert ?? synthesise("ili_alert");

  metrics.air =
    air ??
    remapStatic(staticFb, "air", {
      id: "air",
      label_ko: "대기질 (PM2.5, fallback)",
      label_en: "Air (PM2.5, fallback)",
      unit: "µg/m³",
    }) ??
    synthesise("air");

  metrics.temp =
    tempHumPair.temp ??
    remapStatic(staticFb, "temp", {
      id: "temp",
      label_ko: "기온 (fallback)",
      label_en: "Temperature (fallback)",
      unit: "°C",
    }) ??
    synthesise("temp");

  metrics.humidity = tempHumPair.humidity ?? synthesise("humidity");
  metrics.er = er ?? synthesise("er");
  metrics.metro = metro ?? synthesise("metro");

  return {
    metrics,
    generated_at: new Date().toISOString(),
    ttl_seconds: TTL_SECONDS,
  };
}

// ── ILI model-forecast loader ────────────────────────────────────────

interface IliForecastGu {
  ili: number;
  lo: number;
  hi: number;
}

interface IliForecastJson {
  generated_at: string;
  observed_at: string;
  source: string;
  model: string;
  horizon_weeks: number;
  note?: string;
  gu: Record<string, IliForecastGu>;
}

/**
 * Fetches the pre-computed model-forecast JSON written by
 * build-static-aggregates.py and converts it to a MetricPayload.
 *
 * Args:
 *   origin: request origin for building the absolute static URL.
 *   signal: AbortSignal from the Edge route.
 *
 * Returns:
 *   MetricPayload with source="model-forecast", or null on any failure.
 *
 * Side effects:
 *   One HTTP GET to ``${origin}/aggregates/ili-forecast.json``.
 */
async function buildIliForecast(
  origin: string,
  signal: AbortSignal,
): Promise<MetricPayload | null> {
  let raw: IliForecastJson;
  try {
    const resp = await tfetch(`${origin}/aggregates/ili-forecast.json`, {
      signal,
      timeoutMs: 4000,
      cache: "no-store",
    });
    if (!resp.ok) return null;
    raw = (await resp.json()) as IliForecastJson;
  } catch {
    return null;
  }

  const guData = raw.gu ?? {};
  if (Object.keys(guData).length === 0) return null;

  const observedAt = raw.observed_at ?? "1970-01-01T00:00:00Z";
  // Weekly forecast: allow 8 days as "live" window (freshly generated),
  // 21 days as "stale". Beyond that = offline.
  const freshness = classifyFreshness(observedAt, 60 * 24 * 8, 60 * 24 * 21);

  const rows = SEOUL_GU.filter((gu) => guData[gu] !== undefined).map((gu) => ({
    gu_nm: gu,
    value: Math.round((guData[gu]?.ili ?? 0) * 100) / 100,
  }));

  if (rows.length === 0) return null;

  return {
    id: "ili_forecast",
    label_ko: `ILI 예측 (${raw.model})`,
    label_en: `ILI forecast (${raw.model})`,
    unit: "per 1k",
    source: "model-forecast",
    observed_at: observedAt,
    rows,
    freshness,
    note: raw.note ?? `챔피언 모델: ${raw.model}`,
  };
}

/** Narrow ``safe()`` wrapper — swallow the exception and return
 *  ``defaultValue``. We can't let a provider throw because
 *  ``Promise.all`` would reject the whole orchestrator. */
async function safe<T>(
  fn: () => Promise<T>,
  defaultValue: T,
): Promise<T> {
  try {
    return await fn();
  } catch {
    return defaultValue;
  }
}

async function fetchFallback(
  origin: string,
  signal: AbortSignal,
): Promise<StaticFallbackShape> {
  try {
    const r = await fetch(`${origin}${STATIC_FALLBACK_URL}`, {
      signal,
      cache: "force-cache",
    });
    if (!r.ok) return {};
    return (await r.json()) as StaticFallbackShape;
  } catch {
    return {};
  }
}

/** Narrow a static aggregate entry into a live-style payload. */
function remapStatic(
  fb: StaticFallbackShape,
  staticKey: "ili" | "air" | "temp",
  target: Pick<MetricPayload, "id" | "label_ko" | "label_en" | "unit">,
): MetricPayload | null {
  const src = fb.metrics?.[staticKey];
  if (!src || !src.rows || src.rows.length === 0) return null;
  return {
    id: target.id,
    label_ko: target.label_ko,
    label_en: target.label_en,
    unit: target.unit,
    source: src.source ?? "static_fallback",
    observed_at: fb.generated_at ?? "1970-01-01T00:00:00Z",
    rows: src.rows,
    freshness: "stale",
    note: "static aggregate — no live source configured",
  };
}

// ── Synthetic generator ──────────────────────────────────────────────
// Deterministic per-gu pseudo-values so the map stays populated offline.
// Uses xorshift on a tiny string hash so the numbers are stable across
// reloads (important for screenshots / GIF) but look "random enough".

function hash(s: string, salt: number): number {
  let h = 2166136261 ^ salt;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return (h >>> 0) / 0xffffffff;
}

interface SynthSpec {
  label_ko: string;
  label_en: string;
  unit: string;
  min: number;
  max: number;
  salt: number;
  binary?: boolean;
}

const SYNTH: Record<LiveMetricId, SynthSpec> = {
  ili_forecast: { label_ko: "ILI 예측 (데모)", label_en: "ILI forecast (demo)", unit: "per 1k", min: 2, max: 22, salt: 1 },
  ili_live: { label_ko: "ILI 실측 (데모)", label_en: "ILI observed (demo)", unit: "/1k", min: 1, max: 18, salt: 2 },
  ili_alert: { label_ko: "유행 경보 (데모)", label_en: "Outbreak alert (demo)", unit: "flag", min: 0, max: 1, salt: 3, binary: true },
  air: { label_ko: "대기질 (데모)", label_en: "Air (demo)", unit: "µg/m³", min: 8, max: 45, salt: 4 },
  temp: { label_ko: "기온 (데모)", label_en: "Temperature (demo)", unit: "°C", min: 3, max: 19, salt: 5 },
  humidity: { label_ko: "습도 (데모)", label_en: "Humidity (demo)", unit: "%", min: 28, max: 82, salt: 6 },
  er: { label_ko: "응급실 과밀도 (데모)", label_en: "ER crowding (demo)", unit: "% used", min: 35, max: 95, salt: 7 },
  metro: { label_ko: "지하철 혼잡도 (데모)", label_en: "Subway crowding (demo)", unit: "%", min: 30, max: 90, salt: 8 },
};

function synthesise(id: LiveMetricId): MetricPayload {
  const spec = SYNTH[id];
  const rows = SEOUL_GU.map((gu) => {
    const r = hash(gu, spec.salt);
    const v = spec.binary
      ? r > 0.8 ? 1 : 0
      : spec.min + r * (spec.max - spec.min);
    return { gu_nm: gu, value: Math.round(v * 100) / 100 };
  });
  return {
    id,
    label_ko: spec.label_ko,
    label_en: spec.label_en,
    unit: spec.unit,
    source: "synthetic",
    observed_at: new Date().toISOString(),
    rows,
    freshness: "offline",
    note: "no live source configured — deterministic demo",
  };
}
