/**
 * Local-DB ILI layers (Turso 제거 — 완전 로컬화 2026-06-08).
 *
 *   ``ili_live``  — per-gu observed ILI for the most recent week in
 *                   ``sentinel_influenza`` (KDCA 표본감시), distributed
 *                   across 25 gus using the ABM baseline I_frac pattern.
 *                   Source: ``web/public/aggregates/ili-local.json``
 *                   (regenerated by ``web/scripts/build-static-aggregates.py``).
 *
 *   ``ili_alert`` — gu-level binary threshold flag (observed > q70 of
 *                   rolling 52-week city average, broadcast per gu).
 *
 * Both layers share one fetch so the Edge function stays well under 50 ms.
 * No Turso / libSQL dependency. Falls back to offlinePayload when the
 * static JSON is missing or malformed.
 */
import type { MetricPayload } from "./types";
import { SEOUL_GU, classifyFreshness, tfetch } from "./types";

interface IliLocalGu {
  ili: number;
  q70: number;
  alert: boolean;
}

interface IliLocalJson {
  generated_at: string;
  observed_at: string;
  source: string;
  note?: string;
  gu: Record<string, IliLocalGu>;
}

/**
 * Returns BOTH the observed-rate layer and the alert-flag layer in one
 * call so we only hit the static JSON file once per ISR cycle. Either
 * may be ``null`` when the file is unreachable.
 *
 * Args:
 *   origin: request origin (e.g. "http://localhost:3000"), used to build
 *           the absolute URL for the static JSON fetch.
 *   signal: AbortSignal from the Edge route — propagated to the inner
 *           tfetch so the 3-4 s timeout is respected.
 *
 * Returns:
 *   { live: MetricPayload | null, alert: MetricPayload | null }
 *
 * Side effects:
 *   One HTTP GET to ``${origin}/aggregates/ili-local.json`` per call.
 *   No DB / Turso access.
 */
export async function buildIliLiveAndAlert(
  origin: string,
  signal: AbortSignal,
): Promise<{ live: MetricPayload | null; alert: MetricPayload | null }> {
  let raw: IliLocalJson;
  try {
    const resp = await tfetch(`${origin}/aggregates/ili-local.json`, {
      signal,
      timeoutMs: 4000,
      cache: "no-store",
    });
    if (!resp.ok) {
      return {
        live: offlinePayload(
          "ili_live",
          "ILI 실측 (KDCA)",
          "ILI observed (KDCA)",
          "/1k",
          `ili-local.json fetch failed: HTTP ${resp.status}`,
        ),
        alert: offlinePayload(
          "ili_alert",
          "유행 경보",
          "Outbreak alert",
          "flag",
          `ili-local.json fetch failed: HTTP ${resp.status}`,
        ),
      };
    }
    raw = (await resp.json()) as IliLocalJson;
  } catch (e) {
    const note = e instanceof Error ? e.message : String(e);
    return {
      live: offlinePayload(
        "ili_live",
        "ILI 실측 (KDCA)",
        "ILI observed (KDCA)",
        "/1k",
        `ili-local.json unreachable: ${note}`,
      ),
      alert: offlinePayload(
        "ili_alert",
        "유행 경보",
        "Outbreak alert",
        "flag",
        `ili-local.json unreachable: ${note}`,
      ),
    };
  }

  const guData = raw.gu ?? {};
  if (Object.keys(guData).length === 0) {
    return {
      live: offlinePayload(
        "ili_live",
        "ILI 실측 (KDCA)",
        "ILI observed (KDCA)",
        "/1k",
        "ili-local.json: no gu entries — re-run build-static-aggregates.py",
      ),
      alert: offlinePayload(
        "ili_alert",
        "유행 경보",
        "Outbreak alert",
        "flag",
        "ili-local.json: no gu entries — re-run build-static-aggregates.py",
      ),
    };
  }

  const observedAt = raw.observed_at ?? "1970-01-01T00:00:00Z";
  // Weekly data is at least a day "stale" by construction; bump windows
  // so a freshly-generated snapshot shows LIVE rather than OFFLINE.
  const freshness = classifyFreshness(observedAt, 60 * 24 * 8, 60 * 24 * 21);

  const seoulSet = new Set<string>(SEOUL_GU);

  const liveRows = SEOUL_GU.filter((gu) => seoulSet.has(gu) && guData[gu] !== undefined).map(
    (gu) => ({
      gu_nm: gu,
      value: Math.round((guData[gu]?.ili ?? 0) * 100) / 100,
    }),
  );

  const alertRows = SEOUL_GU.filter((gu) => seoulSet.has(gu) && guData[gu] !== undefined).map(
    (gu) => ({
      gu_nm: gu,
      value: guData[gu]?.alert ? 1 : 0,
    }),
  );

  const weekDate = observedAt.slice(0, 10);

  return {
    live: {
      id: "ili_live",
      label_ko: "ILI 실측 (KDCA)",
      label_en: "ILI observed (KDCA)",
      unit: "/1k",
      source: "local-db",
      observed_at: observedAt,
      rows: liveRows,
      freshness,
      note: raw.note ?? `week of ${weekDate}`,
    },
    alert: {
      id: "ili_alert",
      label_ko: "유행 경보",
      label_en: "Outbreak alert",
      unit: "flag",
      source: "local-db",
      observed_at: observedAt,
      rows: alertRows,
      freshness,
      note: `threshold = gu-level q70 (rolling 52w, city broadcast)`,
    },
  };
}

function offlinePayload(
  id: MetricPayload["id"],
  label_ko: string,
  label_en: string,
  unit: string,
  note: string,
): MetricPayload {
  return {
    id,
    label_ko,
    label_en,
    unit,
    source: "fallback",
    observed_at: "1970-01-01T00:00:00Z",
    rows: [],
    freshness: "offline",
    note,
  };
}
