#!/usr/bin/env python3
"""Verify that every file a shipped document cites actually ships.

A document that sources a number to `aria_grounding.json` is making a checkable
promise: open that file and you will find the number. When the file is not in
the distribution the promise is empty, and worse, it reads as evidence. This is
the failure mode that let `docs/PIPELINE_DB_TO_WEB.md` quote accuracy figures
for a backend the run had skipped — the artifact those numbers supposedly came
from was never there to contradict them.

Two ways references break here:

  - **pruned docs** — the documentation set was cut from 115 files to 15, and
    cross-references into the removed files were left behind.
  - **research-only artifacts** — result files that exist in the working
    repository but are deliberately not distributed (size, or they are
    regenerable), still cited as if a reader could open them.

Both are reported; neither is silently tolerated. A citation that intentionally
points outside the distribution should say so in prose rather than look like a
path the reader can follow.

    python scripts/check_doc_citations.py [--list] [--max N]

Exit 0 when every citation resolves (or is under the allowance), 1 otherwise.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Referenced-but-absent by design, with the reason. Anything here is expected to
# be described in the citing prose as unavailable — the point of the allowance is
# that the reader is told, not that the checker looks away.
ALLOW: dict[str, str] = {
    # Not distributed; SETUP.md §3 explains how to rebuild it from the collectors.
    "simulation/data/db/epi_real_seoul.db": "13 GB, rebuilt by `simulation collect`",
    "epi_real_seoul.db": "13 GB, rebuilt by `simulation collect`",
    # Written by the deploy/preflight scripts when you run them.
    "web/scripts/deploy_report.json": "generated by the deploy script",
    "web/scripts/preflight_local_report.json": "generated by the preflight script",
    "web/scripts/preflight_providers_report.json": "generated by the preflight script",
    "preflight_local_report.json": "generated by the preflight script",
    "preflight_providers_report.json": "generated by the preflight script",
    # Emitted by simulation/r_verification/*.R when the cross-check is run.
    "03_dm_canonical.csv": "emitted by the R cross-check",
    "04_wis_crps_pit.csv": "emitted by the R cross-check",
    "ili_series.csv": "emitted by the R cross-check",
    "model_predictions.csv": "emitted by the R cross-check",
    "model_residuals.csv": "emitted by the R cross-check",
    "npi_window.csv": "emitted by the R cross-check",
    "pi_samples.csv": "emitted by the R cross-check",
    "rt_seir_v2.csv": "emitted by the R cross-check",
    # Model weights are excluded (GitHub's 100 MB limit); training regenerates them.
    "models/champion_log.json": "regenerated by training; models/ is not distributed",
    # Named in §3.3 only to record that the old table cited them and they are not here.
    "aria_grounding.json": "named only as a withdrawn citation",
    "llm_compare_latest/factual_report.json": "named only as a withdrawn citation",
}

# A backticked path ending in one of these is treated as a citation.
SUFFIXES = ("json", "csv", "npy", "parquet", "pkl", "md", "png", "pt", "db")

CITATION = re.compile(r"`([A-Za-z0-9_][A-Za-z0-9_./-]*\.(?:" + "|".join(SUFFIXES) + r"))`")


def tracked_files() -> tuple[set[str], dict[str, list[str]]]:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT,
                         capture_output=True, text=True,
                         encoding="utf-8").stdout.split("\0")
    by_name: dict[str, list[str]] = {}
    for t in out:
        if not t:                      # trailing empty from split("\0")
            continue
        by_name.setdefault(Path(t).name, []).append(t)
    return {t for t in out if t}, by_name


def docs() -> list[Path]:
    out = subprocess.run(["git", "ls-files", "-z", "*.md"], cwd=ROOT,
                         capture_output=True, text=True,
                         encoding="utf-8").stdout.split("\0")
    # Only documents a reader is directed to; per-model generated reports are
    # machine output and cite their own siblings by construction.
    skip = ("simulation/results/", "paper/", "web/node_modules/")
    return [ROOT / f for f in out if f and not f.startswith(skip)]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--list", action="store_true", help="print every unresolved citation")
    ap.add_argument("--max", type=int, default=0, help="allowed unresolved citations")
    args = ap.parse_args()

    tracked, by_name = tracked_files()
    unresolved: dict[str, list[str]] = {}
    total = 0

    for doc in docs():
        rel = doc.relative_to(ROOT).as_posix()
        try:
            text = doc.read_text(encoding="utf-8")
        except OSError:
            continue
        seen: set[str] = set()
        for m in CITATION.finditer(text):
            ref = m.group(1)
            if ref in seen:
                continue
            seen.add(ref)
            total += 1
            if ref in tracked or ref in ALLOW:
                continue
            # A bare filename resolves if exactly that name is tracked anywhere.
            if Path(ref).name in by_name:
                continue
            # A path relative to the citing document's own directory.
            if (doc.parent / ref).exists():
                continue
            unresolved.setdefault(rel, []).append(ref)

    n = sum(len(v) for v in unresolved.values())
    print(f"doc citation check — {total} citations across {len(docs())} documents")
    for rel, refs in sorted(unresolved.items()):
        print(f"  {rel}: {len(refs)} unresolved")
        if args.list:
            for r in sorted(refs):
                print(f"      {r}")
    print(f"  {'unresolved':<12} {n}  (allowed {args.max})")
    return 1 if n > args.max else 0


if __name__ == "__main__":
    raise SystemExit(main())
