#!/usr/bin/env python3
"""Rebuild the R12 comprehensive-evaluation report from what is on disk.

Why this exists: a targeted re-run (`--models NegBinGLM,PoissonAutoreg,FusedEpi`
on 2026-07-14) was not isolated from the full run it was meant to supplement. It
wrote its own narrow state over the full run's phase checkpoints, and R12 —
which reads the in-memory `all_results` and nothing else — then regenerated the
report from an empty dict. MASTER_GRID.csv went from 7,287 rows to 14, the four
figures were not written, and REPORT.md now says "Models evaluated: 0" while
per_model_metrics.csv still holds all 48.

The primary artifact survived because the GLM post-pass updated it surgically,
so the report can be rebuilt from it rather than restored from an archive. That
distinction matters: the nearest archived copy predates the log-link GLM
correction (NegBinGLM WIS 3.9009 there vs 4.5445 now), so restoring it would
quietly undo that work in the report layer.

This calls the real `run_comprehensive_eval` — the report is generated by the
pipeline's own code, not hand-assembled — with `all_results` rebuilt by
`simulation.pipeline.rehydrate`.

    python scripts/regenerate_r12.py [--results-dir DIR] [--dry-run]

Exit 0 on success, 1 if the rebuild produced no models.
"""
from __future__ import annotations

import argparse
import logging
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from simulation.pipeline.rehydrate import rehydrate_all_results  # noqa: E402


class _Config:
    """Minimal stand-in for the pipeline config — R12 reads save_dir only."""

    def __init__(self, save_dir: Path):
        self.save_dir = str(save_dir)

    def get_save_dir(self):
        return Path(self.save_dir)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--results-dir", type=Path, default=ROOT / "simulation" / "results")
    ap.add_argument("--dry-run", action="store_true",
                    help="show what would be rebuilt, write nothing")
    ap.add_argument("--sync-checkpoints", action="store_true",
                    help="also rewrite checkpoint_R9/R10/R12 so they describe "
                         "the same run as the artifacts on disk")
    args = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    # Keep the path repo-relative where possible. R12 and the checkpoints record
    # the paths they wrote, so an absolute results_dir bakes this machine's home
    # directory into shipped result files — which the portability gate rejects,
    # correctly: those files are read on other machines.
    results_dir = args.results_dir.resolve()
    try:
        results_dir = results_dir.relative_to(ROOT)
    except ValueError:
        pass  # outside the repo — nothing to make relative against
    state = rehydrate_all_results(results_dir)

    print(f"rehydrated from {results_dir}")
    for k, v in state.recovered.items():
        print(f"  recovered  {k:22} <- {v}")
    for k, v in state.missing.items():
        print(f"  missing    {k:22} {v}")

    n_models = len(state.results.get("per_model_optimize", {}).get("per_model_configs", {}))
    csv_path = results_dir / "per_model_eval" / "per_model_metrics.csv"
    if not csv_path.exists():
        print(f"\nERROR: {csv_path} is absent — nothing to rebuild from.")
        return 1
    print(f"\nsources: {n_models} per-model configs, metrics CSV {csv_path.name}")

    if args.dry_run:
        print("(--dry-run) stopping before write")
        return 0

    out_dir = results_dir / "comprehensive_eval"
    if out_dir.exists():
        backup = out_dir.with_name("comprehensive_eval.pre_regen")
        if backup.exists():
            shutil.rmtree(backup)
        shutil.copytree(out_dir, backup)
        print(f"backed up existing report -> {backup.name}/")

    from simulation.pipeline.comprehensive_eval import run_comprehensive_eval

    res = run_comprehensive_eval(
        phase1=state.results.get("phase1", {}) or {},
        all_results=state.results,
        config=_Config(results_dir),
    )

    grid = out_dir / "MASTER_GRID.csv"
    rows = sum(1 for _ in grid.open(encoding="utf-8")) - 1 if grid.exists() else 0
    figs = len(list((out_dir / "figures").glob("*.png"))) if (out_dir / "figures").is_dir() else 0
    deep = len(list((out_dir / "per_model").glob("*.md"))) if (out_dir / "per_model").is_dir() else 0
    print(f"\nMASTER_GRID rows : {rows}")
    print(f"figures          : {figs}")
    print(f"per-model reports: {deep}")
    print(f"returned n_models: {res.get('n_models')}")

    if rows < 100:
        print("\nERROR: the rebuild produced almost no rows — not writing this off as success.")
        return 1

    if args.sync_checkpoints:
        _sync_checkpoints(results_dir, state, res)
    return 0


def _sync_checkpoints(results_dir: Path, state, r12_result: dict) -> None:
    """Make checkpoint_R9/R10/R12 describe the same run as the artifacts.

    The targeted re-run left three checkpoints contradicting the results tree:
    R9 listed 3 models instead of the 46 its own per-model files hold, R10 read
    `skipped: filter excluded all` while per_model_metrics.csv held 48 models,
    and R12 said `n_models: 0`. Each is rewritten from the artifact that
    actually survived, and stamped with `regenerated_from` so it is never
    mistaken for the original run's own write.
    """
    from simulation.pipeline.utils.checkpoint import CheckpointManager

    # CheckpointManager appends "checkpoints" itself — pass the results root,
    # not the checkpoints directory, or it writes to checkpoints/checkpoints/.
    ckpt = CheckpointManager(results_dir)
    stamp = "scripts/regenerate_r12.py --sync-checkpoints"

    r9 = dict(state.results.get("per_model_optimize") or {})
    if r9.get("per_model_configs"):
        r9["regenerated_from"] = "per_model_optimal/*.json"
        r9["note"] = stamp
        ckpt.save("R9", r9, "Per-Model Optimize (regenerated)")
        print(f"  synced checkpoint_R9  ({len(r9['per_model_configs'])} models)")

    csv_path = results_dir / "per_model_eval" / "per_model_metrics.csv"
    if csv_path.exists():
        import csv as _csv
        with csv_path.open(encoding="utf-8") as f:
            models = [r["model"] for r in _csv.DictReader(f)]
        r10 = dict(state.results.get("per_model_eval") or {})
        r10.update({
            "n_models": len(models),
            "metrics_csv": str(csv_path),
            "regenerated_from": "per_model_eval/per_model_metrics.csv",
            "note": stamp,
        })
        r10.pop("skipped", None)
        r10.pop("reason", None)
        ckpt.save("R10", r10, "Per-Model Eval (regenerated)")
        print(f"  synced checkpoint_R10 ({len(models)} models)")

    r12 = dict(r12_result or {})
    r12["regenerated_from"] = "comprehensive_eval/ rebuild"
    r12["note"] = stamp
    ckpt.save("R12", r12, "Comprehensive Eval (regenerated)")
    print(f"  synced checkpoint_R12 (n_models={r12.get('n_models')})")


if __name__ == "__main__":
    raise SystemExit(main())
